module.exports = {
	amet: require('./amet'),
	consectetur: require('./consectetur'),
	adipiscing: require('./adipiscing'),
	lobortis: require('./lobortis'),
	in: require('./in'),
	scelerisque: require('./scelerisque'),
	vulputate: require('./vulputate'),
	at: require('./at'),
	facilisis: require('./facilisis'),
	urna: require('./urna'),
	donec: require('./donec'),
	morbi: require('./morbi'),
	eleifend: require('./eleifend'),
	quisque: require('./quisque'),
	justo: require('./justo'),
	vehicula: require('./vehicula'),
	nunc: require('./nunc'),
	pharetra: require('./pharetra'),
	lacus: require('./lacus'),
	pulvinar: require('./pulvinar'),
	ac: require('./ac'),
	at: require('./at'),
	aenean: require('./aenean'),
	odio: require('./odio')
};
