module.exports = {
	dolor: require('./dolor'),
	elit: require('./elit'),
	rutrum: require('./rutrum'),
	interdum: require('./interdum'),
	mollis: require('./mollis'),
	etiam: require('./etiam'),
	nunc: require('./nunc'),
	ornare: require('./ornare'),
	eros: require('./eros'),
	nulla: require('./nulla'),
	pulvinar: require('./pulvinar'),
	aliquet: require('./aliquet'),
	ligula: require('./ligula'),
	ullamcorper: require('./ullamcorper'),
	amet: require('./amet'),
	vulputate: require('./vulputate'),
	lorem: require('./lorem'),
	libero: require('./libero'),
	tincidunt: require('./tincidunt'),
	felis: require('./felis')
};
